# Generated by Django 3.0.1 on 2019-12-19 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openid', models.CharField(max_length=50, unique=True)),
                ('nickname', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
